// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
];

const customers = [
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    name: 'Evil Rabbit',
    email: 'evil@rabbit.com',
    image_url: '/customers/evil-rabbit.png',
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    name: 'Delba de Oliveira',
    email: 'delba@oliveira.com',
    image_url: '/customers/delba-de-oliveira.png',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    name: 'Lee Robinson',
    email: 'lee@robinson.com',
    image_url: '/customers/lee-robinson.png',
  },
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    name: 'Michael Novotny',
    email: 'michael@novotny.com',
    image_url: '/customers/michael-novotny.png',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    name: 'Amy Burns',
    email: 'amy@burns.com',
    image_url: '/customers/amy-burns.png',
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    name: 'Balazs Orban',
    email: 'balazs@orban.com',
    image_url: '/customers/balazs-orban.png',
  },
];

const invoices = [
  {
    customer_id: customers[0].id,
    amount: 15795,
    status: 'pending',
    date: '2022-12-06',
  },
  {
    customer_id: customers[1].id,
    amount: 20348,
    status: 'pending',
    date: '2022-11-14',
  },
  {
    customer_id: customers[4].id,
    amount: 3040,
    status: 'paid',
    date: '2022-10-29',
  },
  {
    customer_id: customers[3].id,
    amount: 44800,
    status: 'paid',
    date: '2023-09-10',
  },
  {
    customer_id: customers[5].id,
    amount: 34577,
    status: 'pending',
    date: '2023-08-05',
  },
  {
    customer_id: customers[2].id,
    amount: 54246,
    status: 'pending',
    date: '2023-07-16',
  },
  {
    customer_id: customers[0].id,
    amount: 666,
    status: 'pending',
    date: '2023-06-27',
  },
  {
    customer_id: customers[3].id,
    amount: 32545,
    status: 'paid',
    date: '2023-06-09',
  },
  {
    customer_id: customers[4].id,
    amount: 1250,
    status: 'paid',
    date: '2023-06-17',
  },
  {
    customer_id: customers[5].id,
    amount: 8546,
    status: 'paid',
    date: '2023-06-07',
  },
  {
    customer_id: customers[1].id,
    amount: 500,
    status: 'paid',
    date: '2023-08-19',
  },
  {
    customer_id: customers[5].id,
    amount: 8945,
    status: 'paid',
    date: '2023-06-03',
  },
  {
    customer_id: customers[2].id,
    amount: 1000,
    status: 'paid',
    date: '2022-06-05',
  },
];

const revenue = [
  { month: 'Jan', revenue: 2000 },
  { month: 'Feb', revenue: 1800 },
  { month: 'Mar', revenue: 2200 },
  { month: 'Apr', revenue: 2500 },
  { month: 'May', revenue: 2300 },
  { month: 'Jun', revenue: 3200 },
  { month: 'Jul', revenue: 3500 },
  { month: 'Aug', revenue: 3700 },
  { month: 'Sep', revenue: 2500 },
  { month: 'Oct', revenue: 2800 },
  { month: 'Nov', revenue: 3000 },
  { month: 'Dec', revenue: 4800 },
];

const places = [
  { visited: false ,place : "Concu"},
  { visited: false ,place : "Blue tokai"},
  { visited: true ,place : "Magnolia"},
  { visited: false ,place : "Beyond Burger Inc"},
  { visited: true ,place : "Chinita"},
  { visited: false ,place : "Baker and charlie"},
  { visited: true ,place : "Hole in the wall"},
  { visited: true ,place : "Zed the Baker"},
  { visited: true ,place : "You Mee"},
  { visited: true ,place : "Pizza4P's"},
  { visited: true ,place : "Naaru"},
  { visited: true ,place : "Ctr"},
  { visited: true ,place : "Veena stores"},
  { visited: true ,place : "Shyamjis Chhole Bhature"},
  { visited: false ,place : "Chula Chowki Da Dhaba"},
  { visited: true ,place : "Burma Burma"},
  { visited: true ,place : "Enne"},
  { visited: false ,place : "Three Dots and a Dash"},
  { visited: false ,place : "13th floor"},
  { visited: true ,place : "Dolci"},
  { visited: false ,place : "Druid Garden"},
  { visited: false ,place : "The French Treaty"},
  { visited: false ,place : "Orah Brew Garden"},
  { visited: false ,place : "Gcbc"},
  { visited: false ,place : "Oia"},
  { visited: true ,place : "Candles"},
  { visited: false ,place : "Kling brewery"},
  { visited: false ,place : "Oney brewhouse"},
  { visited: true ,place : "Suzy Q"},
  { visited: true ,place : "Burger seignuer"},
  { visited: false ,place : "Omega 9"},
  { visited: false ,place : "Kebabci"},
  { visited: false ,place : "Farzi cafe"},
  { visited: false ,place : "Prequel"},
  { visited: false ,place : "Lucky Chan"},
  { visited: false ,place : "Bombay brassiere"},
  { visited: false ,place : "Daddy"},
  { visited: true ,place : "Yuki"},
  { visited: false ,place : "Bameys"},
  { visited: false ,place : "Avocado &Brownies"},
  { visited: false ,place : "Shakesbiere"},
  { visited: true ,place : "Pasta street"},
  { visited: false ,place : "Ferrara"},
  { visited: false ,place : "Dyu art cafe"},
  { visited: false ,place : "Peepai"},
  { visited: false ,place : "Andreas brasseire"},
  { visited: true ,place : "Byg brewski"},
  { visited: true ,place : "Lazy Suzy"},
  { visited: true ,place : "MCD"},
  { visited: true ,place : "Geist"},
  { visited: true ,place : "Toscano"},
  { visited: true ,place : "Cafe Noir"},
  { visited: false ,place : "Chillis"},
  { visited: false ,place : "Klava"},
  { visited: false ,place : "Tiger Yaki"},
  { visited: true ,place : "Spettacolare"},
  { visited: false ,place : "The Reservoire"},
  { visited: false ,place : "Brik Oven"},
  { visited: true ,place : "Smoor"},
  { visited: true ,place : "Milano"},
  { visited: true ,place : "Aubree"},
  { visited: true ,place : "Third Wave"},
  { visited: false ,place : "Now Boarding"},
  { visited: false ,place : "Kopitahm Lah"},
  { visited: false ,place : "Yauthcha"},
  { visited: false ,place : "Daily Sushi"},
  { visited: false ,place : "Neralu Cafe"},
  { visited: false ,place : "Elements Eatery"},
  { visited: false ,place : "Absolut Barbeque"},
  { visited: true ,place : "Water Monkey"},
  { visited: false ,place : "The Green Door Coffee House"},
  { visited: false ,place : "Lavonne Cafe"},
  { visited: false ,place : "The Brown table"},
  { visited: true ,place : "The World Cafe"},
  { visited: true ,place : "Taco Bell"},
  { visited: true ,place : "Corner House"},
]

export { users, customers, invoices, revenue, places};
