name: setup-node
run-name: "Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧"
on: [push]
jobs:
  Unit-Testing-MobileBackend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules and npm cache
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: List the state of node modules if cache miss
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm list || true

      - name: Install dependencies
        run: npm install
